"""Initial migration.

Revision ID: 3e3ea2944cb1
Revises: 
Create Date: 2023-12-12 03:05:38.750205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e3ea2944cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('voterId', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('voterPassword', sa.String(length=20), nullable=False))
        batch_op.drop_column('votersId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('voters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votersId', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False))
        batch_op.drop_column('voterPassword')
        batch_op.drop_column('voterId')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
